<a href="https://colab.research.google.com/github/SangeethaRavikumar/Guvitask/blob/main/GuviNumpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__)
print(np.show_config)

1.21.6
<function show at 0x7f8d83ede5e0>


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
print(x.size)
print(x.itemsize)

10
8


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
print(np.info(np.add))

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
x = np.zeros(10)
x[4] = 1

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
x = np.arange(10,49)
print(x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
x = np.array([1,2,3,4,5])
ans = np.flip(x)
print(ans)


[5 4 3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
x = np.arange(0,9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
x = np.array([[1,2,0],[0,4,0]])
np.nonzero(x)

(array([0, 0, 1]), array([0, 1, 1]))

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
import numpy as np
x = np.random.random((3,3,3))
print(x)

[[[0.1805085  0.62637311 0.69086476]
  [0.47543038 0.27367003 0.64065814]
  [0.65254133 0.34007739 0.15905655]]

 [[0.79888098 0.75951985 0.44245787]
  [0.87149922 0.00579186 0.55674592]
  [0.48242847 0.09411883 0.07027997]]

 [[0.70028469 0.27014312 0.5216092 ]
  [0.62677645 0.85893976 0.20859762]
  [0.0728312  0.05470519 0.6235365 ]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
x = np.random.random((10,10))
xmin,xmax = x.min(),x.max()
print(xmin,xmax)

0.007867319872836842 0.9936054370341892


#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
x = np.random.random((10,10))
ans = x.mean()
print(ans)

0.492459538274409


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
import numpy as np
array = np.array([[0,0,0],[0,0,0]])
x = np.pad(array,pad_width=1,mode = 'constant',constant_values=1)
print(x)

'''x = np.ones((5,5))
x[1:-1,1:-1] = 0
print(x)
'''

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


'x = np.ones((5,5))\nx[1:-1,1:-1] = 0\nprint(x)\n'

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
x = np.ones((5,5))
x = np.pad(x,pad_width = 1,mode = 'constant',constant_values = 0)
print(x)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
print(0*np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
x = np.diag(1 + np.arange(4),k = -1)
print(x)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
x = np.zeros((8,8),dtype = int)
x[1::2,::2] = 1
x[::2,1::2] = 1
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
x = np.tile([[0,1],[1,0]],(4,4))
print(x)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
x = np.random.random((5,5))
xmin ,xmax = x.min(),x.max()
x = (x-xmin) / (xmax - xmin)
print(x)

[[0.00477275 0.98250944 0.6772399  1.         0.39907009]
 [0.64038117 0.82307605 0.12260559 0.26652054 0.22234396]
 [0.49698013 0.27114841 0.         0.88316033 0.19708031]
 [0.66230157 0.63340283 0.56799732 0.56028286 0.93556924]
 [0.84695678 0.01106645 0.34764721 0.0781792  0.32423947]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
RGBA = np.dtype([("red",np.uint8),
                    ("green",np.uint8),
                    ("blue",np.uint8),
                    ("alpha",np.uint8)
                    ])
color = np.array((1,2,3,4),dtype = RGBA)
print(color["red"])
type(color)

1


numpy.ndarray

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
arr1 = np.random.random((5,3))
arr2 = np.random.random((3,2))
#print(arr1 @ arr2)
np.dot(arr1,arr2)

array([[0.62248712, 0.62402687],
       [0.92722716, 0.98143704],
       [0.75276385, 0.82492919],
       [0.71468593, 0.49759525],
       [1.17864356, 0.73736577]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
x = np.arange(16)
x[(3 < x) & (x < 8)] *= -1
print(x)

[ 0  1  2  3 -4 -5 -6 -7  8  9 10 11 12 13 14 15]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

ValueError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0)/np.array(0))
print(np.array(0)//np.array(0))
np.array([np.nan]).astype(int).astype(float)

nan
0


<ipython-input-51-52e5be358f56>:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0)/np.array(0))
<ipython-input-51-52e5be358f56>:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0)//np.array(0))


array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
x = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(x)),x))

[-3. 10.  8.  6. -6. 10.  9. -3.  8.  6.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
x = np.random.randint(0,10,10)
y = np.random.randint(0,10,10)
np.intersect1d(x,y)

array([0, 5, 6, 7, 8, 9])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
defaults = np.seterr(all ='ignore')
x = np.ones(1)/0
_ = np.seterr(**defaults)
with np.errstate(all = 'ignore'):
  np.arange(3) /0

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

<ipython-input-56-16339fbc685e>:1: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(-1) == np.emath.sqrt(-1)


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
#yesterday = np.datetime64('today') - np.deltatime64(1)
today = np.datetime64('today')
#tomorrow = np.datetime64('today') + np.deltatime64(1)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
x = np.arange('2016-07','2016-08',dtype = 'datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A = np.ones(3) * 1
B = np.ones(3) * 2
np.add(A,B,out = B)
np.divide(A,2,out = A)
np.negative(A,out = A)
np.multiply(A,B,out = A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
x = np.random.uniform(0,10,10)
print(x - x%1)
print(x//1)
print(np.floor(x))
print(x.astype(int))
print(np.trunc(x))


[7. 1. 2. 8. 1. 0. 9. 5. 7. 1.]
[7. 1. 2. 8. 1. 0. 9. 5. 7. 1.]
[7. 1. 2. 8. 1. 0. 9. 5. 7. 1.]
[7 1 2 8 1 0 9 5 7 1]
[7. 1. 2. 8. 1. 0. 9. 5. 7. 1.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
x = np.zeros((5,5))
x = x + np.arange(5)
print(x)
x = np.tile(np.arange(0,5),(5,1))
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]
[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generate():
  for x in range(10):
    yield x
x = np.fromiter(generate(),dtype = float, count = -1)
print(x)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
x = np.linspace(0,1,11,endpoint = False)[1:]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
x = np.random.random(10)
x.sort()
print(x)

[0.07068856 0.07278936 0.09479624 0.26200062 0.26632702 0.38865561
 0.61757275 0.7166891  0.71855815 0.87291918]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
x = np.arange(15)
np.add.reduce(x)

105

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
equal = np.allclose(A,B)
print(equal)
equal = np.array_equal(A,B)
print(equal)



False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
x = np.zeros(10)
x.flags.writeable = False
x[0]  = 1

ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
x = np.random.random((10,2))
x , y = x[:,0] , x[:,1]
r = np.sqrt(x**2 + y ** 2)
t = np.arctan2(y,x)
print(r)
print(t)

[0.11895209 0.5078731  0.13929304 0.7288734  0.78747276 0.41857907
 0.74548184 0.95794724 1.16163266 0.99555027]
[1.40504306 0.68145138 0.58462046 0.69374798 0.05726021 0.96660132
 0.72603328 1.1219872  0.79557701 0.19269822]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
x = np.random.random(10)
x[x.argmax()] = 0
print(x)

[0.72402588 0.41918948 0.27189482 0.66809931 0.80489521 0.24303791
 0.53644317 0.04969682 0.75338332 0.        ]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
x = np.zeros((5,5),[('x',float),('y',float)])
x['x'],x['y'] = np.meshgrid(np.linspace(0,1,5),
                            np.linspace(0,1,5))
print(x)


[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
x = np.arange(8)
y = x + 0.5
c = 1.0 / np.subtract.outer(x,y)
print(np.linalg.det(c))

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in[np.int8,np.int32,np.int64]:
  print(np.iinfo(dtype).min)
  print(np.iinfo(dtype).max)
for dtype in [np.float32,np.float64]:
  print(np.finfo(dtype).min)
  print(np.finfo(dtype).max)
  print(np.finfo(dtype).eps)


-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions(threshold = float("inf"))
x = np.zeros((40,40))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
  0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
x = np.arange(100)
v = np.random.uniform(0,100)
index = (np.abs(x-v).argmin())
print(x[index])

66


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
import numpy as np
x = np.zeros(10,[('position',[('x',float,1),
                              ('y',float,1)]),
                  ('color',[('r',float,1),
                              ('g',float,1),
                              ('b',float,1)])])
print(x)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


<ipython-input-3-3e1bfe05fb0c>:2: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  x = np.zeros(10,[('position',[('x',float,1),


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
z = np.random.random((10,2))
x,y = np.atleast_2d(z[:,0],z[:,1])
d = np.sqrt((x - x.T)**2 + (y - y.T)**2)
print(d)

[[0.         0.93575146 0.89798885 0.91754398 0.77603602 0.85517068
  1.05575369 0.45086288 0.63120057 0.88760927]
 [0.93575146 0.         0.54343554 0.1466735  0.77461076 0.81052312
  0.77839625 1.04041595 1.25427042 0.63917867]
 [0.89798885 0.54343554 0.         0.39944634 0.29364795 0.29524657
  0.24598347 0.74499477 0.90669996 0.10231612]
 [0.91754398 0.1466735  0.39944634 0.         0.6452368  0.67485155
  0.6319663  0.95867542 1.16385266 0.49728691]
 [0.77603602 0.77461076 0.29364795 0.6452368  0.         0.07990012
  0.30247109 0.49981645 0.62894714 0.20480128]
 [0.85517068 0.81052312 0.29524657 0.67485155 0.07990012 0.
  0.24103683 0.56208943 0.67195289 0.19473808]
 [1.05575369 0.77839625 0.24598347 0.6319663  0.30247109 0.24103683
  0.         0.80089921 0.91078648 0.18513698]
 [0.45086288 1.04041595 0.74499477 0.95867542 0.49981645 0.56208943
  0.80089921 0.         0.22465907 0.68503312]
 [0.63120057 1.25427042 0.90669996 1.16385266 0.62894714 0.67195289
  0.91078648 0.22465

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
x = (np.random.rand(10)*100).astype(np.float32)
y = x.view(np.int32)
y[:] = x
print(x)

[2.38e-44 5.47e-44 5.04e-44 3.22e-44 7.43e-44 1.28e-43 9.11e-44 1.23e-43
 1.12e-44 1.32e-43]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
s = StringIO(''' 1,2,3,4,5,6, , ,7,8, ,9,10,11''')
x = np.genfromtxt(s,delimiter = ",",dtype = np.int)
print(x)

[ 1  2  3  4  5  6 -1 -1  7  8 -1  9 10 11]


<ipython-input-8-520aff69b99e>:3: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.genfromtxt(s,delimiter = ",",dtype = np.int)


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
x = np.arange(9).reshape(3,3)
for index,value in np.ndenumerate(x):
  print(index,value)
for index in np.ndindex(x.shape):
  print(index,x[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
x, y = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
d = np.sqrt(x*x + y*y)
sigma,mu = 1.0,0.0
g = np.exp(-( (d-mu)** 2) / (2.0 * sigma ** 2))
print(g)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n = 10
p = 3
x = np.zeros((n,n))
np.put(x,np.random.choice(range(n*n),p, replace = False),1)
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
x = np.random.rand(5,10)
y = x = x.mean(axis = 1,keepdims = True)
print(y)

[[0.42040904]
 [0.47235791]
 [0.56824074]
 [0.46591954]
 [0.46232833]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
x = np.random.randint(0,10,(3,3))
print(x)
print(x[x[:,1].argsort()])

[[1 8 0]
 [2 3 0]
 [9 3 4]]
[[2 3 0]
 [9 3 4]
 [1 8 0]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
import numpy as np
x= np.random.randint(0,3,(3,10))
print((~x.any(axis=0)).any())
x= np.array([
            [0,1,np.nan],
            [1,2,np.nan],
             [4,5,np.nan]
              ])
print(np.isnan(x).all(axis=0))


False
[False False  True]


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5124329682218781


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(3,1)
it = np.nditer([A,B,None])
for x,y,z in it:
  z[...] = x+y
print(it.operands[2])

[[0]
 [2]
 [4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class NamedArray(np.ndarray):
  def __new__(cls,array,name = "no name"):
    obj = np.asarray(array).view(cls)
    obj.name = name
    return obj
  def __array_finalize__(self,obj):
    if obj is None:
      return
    self.name = getattr(obj,'name','no name')
Z = NamedArray(np.arange(10), "range_10")
print (Z.name)



range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

[4. 5. 2. 2. 3. 2. 3. 2. 5. 2.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
X  = [1,2,3,4,5,6]
I  = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w , h = 256 , 256
I = np.random.randint(0, 4,(h,w,3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1,3),axis = 0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
 A = np.random.randint(0,10,(3,4,3,4))
 print(A)
 sum = A.sum(axis = (-2,-1))
 print(sum)

[[[[7 0 5 4]
   [7 8 0 0]
   [5 9 1 7]]

  [[3 8 3 8]
   [0 9 7 5]
   [2 2 5 7]]

  [[1 7 5 9]
   [9 1 6 0]
   [1 2 8 5]]

  [[0 4 0 6]
   [5 5 3 6]
   [4 7 3 7]]]


 [[[8 1 6 9]
   [5 2 0 1]
   [2 1 7 4]]

  [[5 8 5 2]
   [0 5 2 7]
   [9 4 5 1]]

  [[8 2 6 9]
   [7 0 6 1]
   [1 0 6 2]]

  [[7 2 6 5]
   [0 9 3 7]
   [9 5 5 2]]]


 [[[2 9 2 8]
   [3 5 7 2]
   [5 1 0 5]]

  [[8 0 8 2]
   [5 6 4 8]
   [1 5 5 2]]

  [[5 0 4 5]
   [9 0 6 8]
   [1 7 6 4]]

  [[8 0 7 9]
   [6 5 8 6]
   [9 8 6 8]]]]
[[53 59 54 50]
 [46 53 48 60]
 [49 54 55 80]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S,weights = D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.60097132 0.39631537 0.39830812 0.49151167 0.45583575 0.34299198
 0.35764858 0.51414366 0.41027161 0.48287966]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([1.0991018 , 0.79672458, 0.85228742, 1.18804771, 1.66830447])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
Z = np.array([1,2,3,4,5])
nz =3
Z0 = np.zeros(len(Z) + (len(Z)-1) * (nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
A = np.ones((5,5,3))
B = 2 * np.ones((5,5))
print(A*B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
A[[0,1]] = A[[1,0]]
print(A)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis =1),-1,axis = 1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis = 1)
G = F.view(dtype = [('p0',F.dtype),('p1',F.dtype)])
G = np.unique(G)
print(G)

[( 1, 21) ( 1, 55) ( 4, 72) ( 4, 92) ( 5, 47) ( 5, 77) (21, 55) (22, 50)
 (22, 58) (23, 27) (23, 53) (25, 65) (25, 78) (27, 52) (27, 53) (27, 95)
 (42, 83) (42, 99) (46, 57) (46, 94) (47, 49) (47, 77) (47, 90) (49, 90)
 (50, 58) (52, 95) (57, 94) (65, 78) (72, 92) (83, 99)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)),C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
import numpy as np
from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
Z = np.arange(10)
print(sliding_window_view(Z,window_shape = 3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
Z = np.random.randint(0,2,100)
np.negative(Z,out =Z)

array([ 0, -1, -1, -1, -1,  0,  0,  0,  0, -1,  0, -1,  0, -1, -1,  0,  0,
       -1, -1, -1, -1, -1, -1,  0, -1,  0, -1, -1,  0,  0,  0, -1,  0,  0,
       -1, -1,  0, -1,  0,  0,  0,  0,  0,  0, -1,  0,  0, -1, -1, -1,  0,
        0,  0, -1,  0,  0,  0, -1,  0, -1,  0, -1, -1,  0,  0,  0, -1,  0,
       -1, -1,  0,  0, -1, -1, -1,  0,  0,  0, -1, -1, -1, -1,  0,  0,  0,
        0,  0,  0, -1, -1,  0,  0, -1, -1, -1, -1,  0, -1, -1, -1])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(P0,P1,p):
  T = P1 -P0
  L = (T**2).sum(axis = 1)
  U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1])/L
  U = U.reshape(len(U),1)
  D = P0 + U*T - p
  return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,( 1,2))
print(distance(P0,P1,p))

[13.05436562  3.62330648 14.54391962  1.13177768 15.97381086  9.32214681
 12.72058078  0.55581958 12.22582116  7.6341198 ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10,10,( 1,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[ 2.85103181  0.88284559  3.60602224  4.93058267 10.26546136  5.89335346
   4.03537364 13.64819355  3.58265287  5.91608829]]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[5 0 0 0 0 1 2 8 2 2]
 [3 1 0 5 0 3 1 1 3 3]
 [9 2 3 7 0 1 8 5 6 6]
 [9 4 6 8 3 2 3 5 8 6]
 [5 1 7 0 1 9 8 4 8 4]
 [5 8 5 3 3 4 9 9 4 4]
 [0 6 5 4 4 9 9 0 1 0]
 [2 8 1 5 3 1 5 2 7 4]
 [7 6 4 8 0 6 7 0 8 7]
 [4 7 3 6 4 0 5 1 9 7]]
[[0 0 0 0 0]
 [0 5 0 0 0]
 [0 3 1 0 5]
 [0 9 2 3 7]
 [0 9 4 6 8]]


<ipython-input-10-f2b5781f38bf>:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  R[r] = Z[z]


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.arange(1,15, dtype = np.uint32)
print(sliding_window_view(Z, window_shape =4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
rank = np.linalg.matrix_rank(Z)
print(rank)

10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape = (3,3)))

[[[[2 0 1]
   [0 2 3]
   [0 2 1]]

  [[0 1 4]
   [2 3 4]
   [2 1 0]]

  [[1 4 4]
   [3 4 1]
   [1 0 1]]

  [[4 4 3]
   [4 1 3]
   [0 1 3]]

  [[4 3 2]
   [1 3 3]
   [1 3 4]]

  [[3 2 1]
   [3 3 0]
   [3 4 3]]

  [[2 1 3]
   [3 0 2]
   [4 3 0]]

  [[1 3 1]
   [0 2 2]
   [3 0 0]]]


 [[[0 2 3]
   [0 2 1]
   [2 3 4]]

  [[2 3 4]
   [2 1 0]
   [3 4 4]]

  [[3 4 1]
   [1 0 1]
   [4 4 1]]

  [[4 1 3]
   [0 1 3]
   [4 1 2]]

  [[1 3 3]
   [1 3 4]
   [1 2 2]]

  [[3 3 0]
   [3 4 3]
   [2 2 1]]

  [[3 0 2]
   [4 3 0]
   [2 1 0]]

  [[0 2 2]
   [3 0 0]
   [1 0 4]]]


 [[[0 2 1]
   [2 3 4]
   [1 1 4]]

  [[2 1 0]
   [3 4 4]
   [1 4 0]]

  [[1 0 1]
   [4 4 1]
   [4 0 3]]

  [[0 1 3]
   [4 1 2]
   [0 3 3]]

  [[1 3 4]
   [1 2 2]
   [3 3 2]]

  [[3 4 3]
   [2 2 1]
   [3 2 1]]

  [[4 3 0]
   [2 1 0]
   [2 1 3]]

  [[3 0 0]
   [1 0 4]
   [1 3 2]]]


 [[[2 3 4]
   [1 1 4]
   [3 4 4]]

  [[3 4 4]
   [1 4 0]
   [4 4 1]]

  [[4 4 1]
   [4 0 3]
   [4 1 0]]

  [[4 1 2]
   [0 3 3]
   [1 0 3]]

  [[1 2 2]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [ ]:
import numpy as np
class Symetric(np.ndarray):
  def __setitem__(self , index , value):
    i,j = index
    super(Symetric, self).__setitem__((i,j),value)
    super(Symetric, self).__setitem__((j,i),value) 
def symetric (Z):
  return np.asarray(Z +Z.T -np.diag(Z.diagonal())).view(Symetric)
S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S) 

[[ 2  9  4 12  8]
 [ 9  2  4 12  6]
 [ 4  4  6 42  8]
 [12 12 42  8  9]
 [ 8  6  8  9  8]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
p ,n = 10,20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M,V,axes = [[0,2],[0,1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z,np.arange(0,Z.shape[0],k),axis =0),np.arange(0, Z.shape[1],k), axis =1)
print(S)

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
Z  = np.arange(10000)
np.random.shuffle(Z)
n =5
print(Z[np.argsort(Z)[-n:]])
print(Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9997 9999 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
Z = np.array([("hello",2.5,3),
              ("World",3.6,2)])
R = np.core.records.fromarrays(Z.T,names = 'col1 ,col2,col3',formats = 'S8 ,f8 ,i8')
print(R)

[(b'hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

1.34 s ± 188 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
212 ms ± 13.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
184 ms ± 6.67 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[1 2 4 5 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[4 0 1]
 [1 0 0]
 [4 2 1]
 [0 1 0]
 [4 4 1]
 [1 4 4]
 [2 1 0]
 [1 4 0]
 [1 4 1]
 [4 0 1]]
[[4 0 1]
 [1 0 0]
 [4 2 1]
 [0 1 0]
 [4 4 1]
 [1 4 4]
 [2 1 0]
 [1 4 0]
 [1 4 1]
 [4 0 1]]
[[4 0 1]
 [1 0 0]
 [4 2 1]
 [0 1 0]
 [4 4 1]
 [1 4 4]
 [2 1 0]
 [1 4 0]
 [1 4 1]
 [4 0 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
I = np.array([0,1,2,3,15,16,32,64,128])
B = ((I.reshape(-1,1)&(2**np.arange(8)))!= 0).astype(int)
print(B[:,::-1])

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 1]
 [0 1 0]
 [0 1 1]
 [1 0 0]
 [1 0 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.1799827 , 0.14712822, 0.31686999, 0.09815438, 0.16363449,
        0.2137791 , 0.22522732, 0.2592529 , 0.29004261, 0.24983062],
       [0.5203208 , 0.42534019, 0.91605497, 0.2837593 , 0.47305895,
        0.61802447, 0.65112069, 0.74948691, 0.83849839, 0.72224758],
       [0.47552248, 0.38871946, 0.83718493, 0.25932833, 0.43232976,
        0.56481411, 0.59506082, 0.68495796, 0.76630578, 0.66006387],
       [0.36988155, 0.30236248, 0.65119794, 0.20171658, 0.33628442,
        0.43933637, 0.46286355, 0.53278935, 0.59606514, 0.51342567],
       [0.12341707, 0.10088822, 0.21728292, 0.06730606, 0.11220684,
        0.14659182, 0.15444205, 0.17777395, 0.19888695, 0.17131294],
       [0.11165963, 0.09127702, 0.19658327, 0.06089409, 0.10151735,
        0.13262661, 0.13972899, 0.16083815, 0.17993981, 0.15499265],
       [0.30775477, 0.25157648, 0.54182014, 0.16783546, 0.27980075,
        0.36554368, 0.38511914, 0.44329993, 0.49594766, 0.42718865],
       [0.28935065, 0.23653188, 0.5094186

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                
r_int = np.linspace(0, r.max(), 200)
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.1615977  0.1970367]
